git fetch team1 master:team1
git fetch team2 master:team2
git fetch team3 master:team3
git fetch team4 master:team4
git fetch team5 master:team5
git fetch team6 master:team6
git fetch team7 master:team7
git fetch team8 master:team8
git fetch teamA master:teamA
git fetch teamB master:teamB
git fetch teamC master:teamC
git fetch teamD master:teamD
git fetch final master:final